region: ap-northeast-1
cluster: estra-prod-estra
service: estra-prod-estra
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m0s
plugins:
  - name: tfstate
    config:
      url: s3://estra-tfstate/estra/prod/cicd/app_estra_v1.0.0.tfstate
